name: dp_algebra

services:
  frontend:
    image: ghcr.io/jimmyl0l3c/dp_algebra-app:latest
    build: ./flutter_app
    container_name: algebra_app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flutter.rule=Host(`algebra.joska.dev`)"
      - "traefik.http.routers.flutter.tls=true"
      - "traefik.http.routers.flutter.tls.certresolver=letsencrypt"

  api:
    image: ghcr.io/jimmyl0l3c/dp_algebra-api:latest
    build: ./backend
    container_name: algebra_api
    restart: unless-stopped
    volumes:
      - backend_user_data:/home/app/web/user_files/:z
      - db_data:/home/app/web/db.sqlite3
    environment:
      - DJANGO_ALLOWED_HOSTS=.joska.dev
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django2.rule=Host(`algebra2.joska.dev`)"
      - "traefik.http.routers.django2.tls=true"
      - "traefik.http.routers.django2.tls.certresolver=letsencrypt"
      - "traefik.http.routers.django.rule=Host(`api.algebra.joska.dev`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

volumes:
  backend_user_data:
  db_data:

networks:
  default:
    name: traefik_default
    external: true
