name: dp_algebra

services:
  frontend:
    image: ghcr.io/jimmyl0l3c/dp_algebra-app:latest
    build: ./flutter_app
    container_name: algebra_app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flutter.rule=Host(`algebra.joska.dev`)"
      - "traefik.http.routers.flutter.tls=true"
      - "traefik.http.routers.flutter.tls.certresolver=letsencrypt"

  api:
    image: ghcr.io/jimmyl0l3c/dp_algebra-api:latest
    build: ./backend
    container_name: algebra_api
    restart: unless-stopped
    volumes:
      - backend_user_data:/home/app/web/user_files/:z
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/algebra_db
      - DJANGO_ALLOWED_HOSTS=.joska.dev
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG=False
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`algebra2.joska.dev`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  db:
    image: postgres:15-alpine
    container_name: algebra_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=algebra_db

volumes:
  postgres_data:
  backend_user_data:

networks:
  default:
    name: traefik_default
    external: true
