# Generated by Django 4.1.7 on 2023-03-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_learnimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnimage',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
