# Generated by Django 4.1.7 on 2023-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_learnimage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='figure',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
