# Generated by Django 4.1.7 on 2023-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_remove_learnimage_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["chapter__order", "order"]},
        ),
        migrations.AlterModelOptions(
            name="articletranslation",
            options={"ordering": ["language"]},
        ),
        migrations.AlterModelOptions(
            name="block",
            options={
                "ordering": [
                    "page__article__chapter__order",
                    "page__article__order",
                    "page__order",
                    "order",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="blocktranslation",
            options={"ordering": ["language"]},
        ),
        migrations.AlterModelOptions(
            name="blocktype",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="blocktypetranslation",
            options={"ordering": ["language"]},
        ),
        migrations.AlterModelOptions(
            name="chaptertranslation",
            options={"ordering": ["language"]},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="learnimage",
            options={"ordering": ["ref_name"]},
        ),
        migrations.AlterModelOptions(
            name="literature",
            options={"ordering": ["ref_name"]},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["article__chapter__order", "article__order", "order"]
            },
        ),
        migrations.AlterModelOptions(
            name="reflabel",
            options={"ordering": ["block"]},
        ),
        migrations.AddField(
            model_name="block",
            name="ref_label",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blocktype",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
