# Generated by Django 4.1.7 on 2023-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0013_delete_reflabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktype",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
